let's see if the errors are corrected

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -38,17 +38,38 @@ jobs:
       run: |
         git config --global user.name "GitHub Action"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
         if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
-          echo "::set-output name=SRC_BRANCH::${GITHUB_HEAD_REF}"
-          echo "::set-output name=NO_PUSH::--no-push"
+          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> "$GITHUB_OUTPUT"
+          echo "NO_PUSH=--no-push" >> "$GITHUB_OUTPUT"
         elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
-          echo "::set-output name=SRC_BRANCH::${GITHUB_REF#refs/heads/}"
+          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"
         fi
-        echo "::set-output name=DEPLOY_BRANCH::gh-pages"
+
+        echo "DEPLOY_BRANCH=gh-pages" >> "$GITHUB_OUTPUT"
+    # Deprecated syntax
+    # - name: Setup deploy options
+    #   id: setup
+    #   run: |
+    #     git config --global user.name "GitHub Action"
+    #     git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+    #     if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
+    #       echo "::set-output name=SRC_BRANCH::${GITHUB_HEAD_REF}"
+    #       echo "::set-output name=NO_PUSH::--no-push"
+    #     elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
+    #       echo "::set-output name=SRC_BRANCH::${GITHUB_REF#refs/heads/}"
+    #     fi
+    #     echo "::set-output name=DEPLOY_BRANCH::gh-pages"
+    
+    # If no changes to commit, git commit will return non-zero exit code
+    # - name: Fix permissions
+    #   run: |
+    #     chmod a+x bin/*
+    #     git commit -am "add execute permission to bin/deploy"  
     - name: Fix permissions
       run: |
         chmod a+x bin/*
-        git commit -am "add execute permission to bin/deploy"  
+        git commit -am "add execute permission to bin/deploy" || echo "nothing to commit"
     - name: Deploy website 
       run:  yes | bash bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }}
                     --src ${{ steps.setup.outputs.SRC_BRANCH }} 
